name: ManHunters
version: 1.2
website: 'https://sirblob.bosstop.ml'
main: ml.bosstop.manhunters.ManHunters
author: Sir_Blob_

commands:
  manhunt:
    description: ManHunt command
    usage: /manhunt <start|stop|join|leave|list|help>
    aliases: [mh]
    default: true